name: content_brief_gen
description: CLI tool to fetch Google search suggestions and create SEO keyword lists.
version: 3.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.0
  html: ^0.15.4
  intl: ^0.19.0
  anthropic_sdk_dart: ^0.2.1
  googleai_dart: ^0.1.3
  docx_template: ^0.4.0
